[project]
name = "vla"
version = "0.0.1"
dependencies = ["typer", 
                "rich",
                "fastapi",
                "uvicorn",
                "requests",
                "numpy",
                "pillow",
                "huggingface_hub",
                "docker"]

[project.scripts]
vla = "vla.cmd.vla_cli:main"